language: ruby
bundler_args: --without development
before_install:
  - gem install bundler
  - gem update --system

matrix:
  include:
    - rvm: 2.1.10
    - rvm: 2.2.6
    - rvm: 2.3.3
    - rvm: 2.4.0
    - rvm: jruby-9.1.12.0
      env:
        - JRUBY_OPTS="--server -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -J-Xms512m -J-Xmx1024m"
    - rvm: ruby-head

branches:
  only:
    - master
