language: ruby
bundler_args: --without development
before_install:
  - gem install bundler
  - gem update --system

matrix:
  include:
    - rvm: 2.2.10
    - rvm: 2.3.8
    - rvm: 2.4.10
    - rvm: 2.5.8
    - rvm: 2.6.6
    - rvm: 2.7.2
    - rvm: 3.0.0
    - rvm: jruby-9.2.18.0
      env:
        - JRUBY_OPTS="--server -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -J-Xms512m -J-Xmx1024m"
    - rvm: ruby-head

branches:
  only:
    - master
    - 1.2-stable
    - 2.0-develop
